apiVersion: v1
kind: PersistentVolume
metadata:
  name: scanagroempresa-dbbackups
spec:
  storageClassName: local-storage
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/tmp/sae-dbbackups
    type: DirectoryOrCreate
