apiVersion: v1
kind: PersistentVolume
metadata:
  name: scanagroempresa-geonode-ssh-config
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/tmp/sae-geonode-ssh-config
    type: DirectoryOrCreate
