apiVersion: v1
kind: PersistentVolume
metadata:
  name: scanagroempresa-geoserver-data-dir
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/tmp/sae-geoserver-data-dir
    type: DirectoryOrCreate
