apiVersion: v1
kind: PersistentVolume
metadata:
  name: scanagroempresa-django
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/tmp/sae-django
    type: DirectoryOrCreate
