apiVersion: v1
kind: PersistentVolume
metadata:
  name: scanagroempresa-redis-data
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/tmp/sae-redis-data
    type: DirectoryOrCreate
