apiVersion: v1
kind: PersistentVolume
metadata:
  name: templates
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/tmp/sae-templates
    type: DirectoryOrCreate
