apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
            --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
            --output-file parse2-scanagroempresa.PROD
        kompose.version: 1.21.0 (992df58d8)
        org.geonode.component: backup
        org.geonode.instance.name: geonode
    creationTimestamp: null
    labels:
        io.kompose.service: backup-db
    name: backup-db
spec:
    selector:
        matchLabels:
            io.kompose.service: backup-db
    strategy:
        type: Recreate
    template:
        metadata:
            annotations:
                kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
                    --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
                    --output-file parse2-scanagroempresa.PROD
                kompose.version: 1.21.0 (992df58d8)
                org.geonode.component: backup
                org.geonode.instance.name: geonode
            creationTimestamp: null
            labels:
                io.kompose.service: backup-db
        spec:
            imagePullSecrets:
            - name: dockerhub
            containers:
              - env:
                  - name: ARCHIVE_FILENAME
                    value: /backups/PG_scanagroempresa
                  - name: DUMPPREFIX
                    value: PG_scanagroempresa
                  - name: PGHOST
                    value: db
                  - name: PGPASSWORD
                    value: postgres
                  - name: PGPORT
                    value: "5432"
                  - name: PGUSER
                    value: postgres
                  - name: POSTGRES_DBNAME
                    value: geonode
                  - name: POSTGRES_HOST
                    value: db
                  - name: POSTGRES_PASS
                    value: postgres
                  - name: POSTGRES_PORT
                    value: "5432"
                  - name: POSTGRES_USER
                    value: postgres
                  - name: WITH_POSTGIS
                    value: "1"
                image: kartoza/pg-backup:9.6
                imagePullPolicy: ""
                name: backup-db
                resources: {}
                stdin: true
                volumeMounts:
                  - mountPath: /backups
                    name: scanagroempresa-dbbackups
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: scanagroempresa-dbbackups
                persistentVolumeClaim:
                    claimName: scanagroempresa-dbbackups
status: {}
