apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        io.rancher.container.pull_image: always
        kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
            --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
            --output-file parse2-scanagroempresa.PROD
        kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
        io.kompose.service: borg-backup-service-server
    name: borg-backup-service-server
spec:
    selector:
        matchLabels:
            io.kompose.service: borg-backup-service-server
    strategy:
        type: Recreate
    template:
        metadata:
            annotations:
                io.rancher.container.pull_image: always
                kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
                    --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
                    --output-file parse2-scanagroempresa.PROD
                kompose.version: 1.21.0 (992df58d8)
            creationTimestamp: null
            labels:
                io.kompose.service: borg-backup-service-server
        spec:
            imagePullSecrets:
            - name: dockerhub
            containers:
              - env:
                  - name: ARCHIVE_PREFIX
                    value: kobotoolbox
                  - name: BORG_PASSPHRASE
                    value: UioAlHICpwn3UoTNr8pQhghJdBx3393j
                  - name: BORG_RELOCATED_REPO_ACCESS_IS_OK
                    value: yes
                  - name: BORG_REPO
                    value: /borg/repo
                  - name: USERS
                    value: root
                image: lucernae/borgbackup:1.1.8
                imagePullPolicy: ""
                name: borg-backup-service-server
                resources: {}
                volumeMounts:
                  - mountPath: /root
                    name: scanagroempresa-borg-users-home
                  - mountPath: /borg/repo
                    name: scanagroempresa-borg-repo
                  - mountPath: /root/.cache/borg
                    name: scanagroempresa-borg-cache
                  - mountPath: /borg/data/geoserver-data-dir
                    name: scanagroempresa-geoserver-data-dir
                  - mountPath: /borg/data/statics
                    name: scanagroempresa-statics
                  - mountPath: /borg/data/dbbackups
                    name: scanagroempresa-dbbackups
                  - mountPath: /borg/data/templates
                    name: templates
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: scanagroempresa-borg-users-home
                persistentVolumeClaim:
                    claimName: scanagroempresa-borg-users-home
              - name: scanagroempresa-borg-repo
                persistentVolumeClaim:
                    claimName: scanagroempresa-borg-repo
              - name: scanagroempresa-borg-cache
                persistentVolumeClaim:
                    claimName: scanagroempresa-borg-cache
              - name: scanagroempresa-geoserver-data-dir
                persistentVolumeClaim:
                    claimName: scanagroempresa-geoserver-data-dir
              - name: scanagroempresa-statics
                persistentVolumeClaim:
                    claimName: scanagroempresa-statics
              - name: scanagroempresa-dbbackups
                persistentVolumeClaim:
                    claimName: scanagroempresa-dbbackups
              - name: templates
                persistentVolumeClaim:
                    claimName: templates
status: {}
