apiVersion: apps/v1
kind: Deployment
metadata:
    # annotations:
    #     io.rancher.container.pull_image: always
    #     io.rancher.container.start_once: "true"
    #     io.rancher.scheduler.affinity:host_label: geonode.production=geonode
    #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
    #         --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
    #         --output-file parse2-scanagroempresa.PROD
    #     kompose.version: 1.21.0 (992df58d8)
    #     org.geonode.component: conf
    #     org.geonode.instance.name: geonode
    # creationTimestamp: null
    labels:
        io.kompose.service: data-dir-conf
    name: data-dir-conf
    namespace: scanagroempresa
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: data-dir-conf
    strategy:
        type: Recreate
    template:
        metadata:
            # annotations:
            #     io.rancher.container.pull_image: always
            #     io.rancher.container.start_once: "true"
            #     io.rancher.scheduler.affinity:host_label: geonode.production=geonode
            #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
            #         --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
            #         --output-file parse2-scanagroempresa.PROD
            #     kompose.version: 1.21.0 (992df58d8)
            #     org.geonode.component: conf
            #     org.geonode.instance.name: geonode
            # creationTimestamp: null
            labels:
                io.kompose.service: data-dir-conf
        spec:
            imagePullSecrets:
              - name: dockerhub
            containers:
              - args:
                  - /bin/true
                image: scanterra/geoserver_data:2.13.x
                imagePullPolicy: Always
                name: data-dir-conf
                resources: {}
                volumeMounts:
                  - mountPath: /geoserver_data/data
                    name: scanagroempresa-geoserver-data-dir
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: scanagroempresa-geoserver-data-dir
                persistentVolumeClaim:
                    claimName: scanagroempresa-geoserver-data-dir
status: {}
