apiVersion: apps/v1
kind: Deployment
metadata:
    # annotations:
    #     io.rancher.container.pull_image: always
    #     io.rancher.scheduler.affinity:host_label: geonode.production=geonode
    #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
    #         --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
    #         --output-file parse2-scanagroempresa.PROD
    #     kompose.version: 1.21.0 (992df58d8)
    #     org.geonode.component: geoserver
    #     org.geonode.instance.name: geonode
    # creationTimestamp: null
    labels:
        io.kompose.service: geoserver
    name: geoserver
    namespace: scanagroempresa
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: geoserver
    strategy:
        type: Recreate
    template:
        metadata:
            # annotations:
            #     io.rancher.container.pull_image: always
            #     io.rancher.scheduler.affinity:host_label: geonode.production=geonode
            #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
            #         --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
            #         --output-file parse2-scanagroempresa.PROD
            #     kompose.version: 1.21.0 (992df58d8)
            #     org.geonode.component: geoserver
            #     org.geonode.instance.name: geonode
            # creationTimestamp: null
            labels:
                io.kompose.service: geoserver
        spec:
            imagePullSecrets:
              - name: dockerhub
            containers:
              - env:
                  - name: GEOSERVER_ADMIN_PASSWORD
                    value: 9Jk*8$k!mlXdgmQiPqya
                  - name: NGINX_BASE_URL
                    value: https://local.scanagroempresa.scanterra.com/
                image: scanterra/geoserver-docker:2.13.x
                imagePullPolicy: Always
                name: geoserver
                resources: {}
                stdin: true
                volumeMounts:
                  - mountPath: /geoserver_data/data
                    name: scanagroempresa-geoserver-data-dir
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: scanagroempresa-geoserver-data-dir
                persistentVolumeClaim:
                    claimName: scanagroempresa-geoserver-data-dir
            affinity:
              nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                          - key: geonode.production
                            operator: In
                            values:
                            - geonode
status: {}
