apiVersion: apps/v1
kind: Deployment
metadata:
    # annotations:
    #     cron.action: restart
    #     cron.schedule: 0 */5 * * * ?
    #     io.rancher.container.pull_image: always
    #     io.rancher.container.start_once: "true"
    #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
    #         --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
    #         --output-file parse2-scanagroempresa.PROD
    #     kompose.version: 1.21.0 (992df58d8)
    # creationTimestamp: null
    labels:
        io.kompose.service: kobo-extractor
    name: kobo-extractor
    namespace: scanagroempresa
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: kobo-extractor
    strategy:
        type: Recreate
    template:
        metadata:
            # annotations:
            #     cron.action: restart
            #     cron.schedule: 0 */5 * * * ?
            #     io.rancher.container.pull_image: always
            #     io.rancher.container.start_once: "true"
            #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
            #         --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
            #         --output-file parse2-scanagroempresa.PROD
            #     kompose.version: 1.21.0 (992df58d8)
            # creationTimestamp: null
            labels:
                io.kompose.service: kobo-extractor
        spec:
            imagePullSecrets:
            - name: dockerhub
            containers:
              - args:
                  - python
                  - manage.py
                  - kobo_extractor
                env:
                  - name: ALLOWED_HOSTS
                    value: '[''.scanterra.com'']'
                  - name: DATA_PGDATABASE
                    value: kobo_form_data
                  - name: DATA_PGHOST
                    value: db
                  - name: DATA_PGPASSWORD
                    value: postgres
                  - name: DATA_PGPORT
                    value: "5432"
                  - name: DATA_PGUSER
                    value: postgres
                  - name: DJANGO_SECRET_KEY
                    value: sae8c0#cb&d-yt=d)vwf%8ks(rn_+++$za5(mv(2g#-1l9k2%f)vs
                  - name: DJANGO_SETTINGS_MODULE
                    value: scanterra.settings_prod
                  - name: GEONODE_ADMIN_PASSWORD
                    value: '@ScanTerra2019'
                  - name: GEONODE_ADMIN_USER
                    value: admin
                  - name: GEONODE_CSRF_COOKIE_NAME
                    value: csrftoken_geonode
                  - name: GEONODE_INDEX_PREFIX
                    value: administration/
                  - name: GEONODE_PGDATABASE
                    value: geonode
                  - name: GEONODE_PGHOST
                    value: db
                  - name: GEONODE_PGPASSWORD
                    value: postgres
                  - name: GEONODE_PGPORT
                    value: "5432"
                  - name: GEONODE_PGUSER
                    value: postgres
                  - name: GEONODE_SERVER_HOST
                    value: http://geonode
                  - name: GEONODE_SERVER_PUBLIC_HOST
                    value: https://local.scanagroempresa.scanterra.com
                  - name: GEOSERVER_ADMIN_PASSWORD
                    value: 9Jk*8$k!mlXdgmQiPqya
                  - name: GEOSERVER_ADMIN_USER
                    value: admin
                  - name: GEOSERVER_HOST
                    value: https://local.scanagroempresa.scanterra.com/geoserver
                  - name: GEOSERVER_SERVER_HOST
                    value: https://local.scanagroempresa.scanterra.com/geoserver
                  - name: KOBO_API_TOKEN
                    value: a3e4cf35950304fe709a9cd9ea2b4b6426ea8d21
                  - name: KOBO_API_URL
                    value: https://local.scancollect.scanterra.com
                  - name: KOBO_PGDATABASE
                    value: kobotoolbox
                  - name: KOBO_PGHOST
                    value: postgres.kobotoolbox
                  - name: KOBO_PGPASSWORD
                    value: 2iPKRYvECdJLHspsX5Uj0QKs5EJ1Ztqt
                  - name: KOBO_PGPORT
                    value: "5432"
                  - name: KOBO_PGUSER
                    value: report_user
                  - name: KPI_URL
                    value: https://local.scancollect-form-edit.scanterra.com
                  - name: MEDIA_ROOT
                    value: /home/web/media
                  - name: PGDATABASE
                    value: scanweb
                  - name: PGHOST
                    value: db
                  - name: PGPASSWORD
                    value: postgres
                  - name: PGPORT
                    value: "5432"
                  - name: PGUSER
                    value: postgres
                  - name: PYTHONPATH
                    value: /home/web/extra_app
                  - name: REDIS_DEFAULT_DB
                    value: "1"
                  - name: REDIS_HOST
                    value: redis
                  - name: REDIS_PORT
                    value: "6379"
                  - name: REDIS_SESSION_DB
                    value: "2"
                  - name: ROOT_URLCONF
                    value: scanterra.root_urls
                  - name: SITEURL
                    value: https://local.scanagroempresa.scanterra.com
                  - name: STATIC_ROOT
                    value: /home/web/static
                  - name: URL_PREFIX
                    value: scanagroempresa/
                image: scanterra/kobo_extractor:develop
                imagePullPolicy: Always
                name: kobo-extractor
                resources: {}
                volumeMounts:
                  - mountPath: /home/web/static
                    name: scanagroempresa-scanagroempresa-statics
                  - mountPath: /root/.ssh
                    name: scanagroempresa-scanagroempresa-ssh-config
                workingDir: /home/web/extra_app
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: scanagroempresa-scanagroempresa-statics
                persistentVolumeClaim:
                    claimName: scanagroempresa-scanagroempresa-statics
              - name: scanagroempresa-scanagroempresa-ssh-config
                persistentVolumeClaim:
                    claimName: scanagroempresa-scanagroempresa-ssh-config
status: {}
