apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
            --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
            --output-file parse2-scanagroempresa.PROD
        kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
        io.kompose.service: rabbitmq
    name: rabbitmq
spec:
    selector:
        matchLabels:
            io.kompose.service: rabbitmq
    strategy: {}
    template:
        metadata:
            annotations:
                kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
                    --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
                    --output-file parse2-scanagroempresa.PROD
                kompose.version: 1.21.0 (992df58d8)
            creationTimestamp: null
            labels:
                io.kompose.service: rabbitmq
        spec:
            imagePullSecrets:
              - name: dockerhub
            containers:
              - image: rabbitmq:3.6
                imagePullPolicy: ""
                name: rabbitmq
                resources: {}
            restartPolicy: Always
            serviceAccountName: ""
            volumes: null
status: {}
