apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
            --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
            --output-file parse2-scanagroempresa.PROD
        kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
        io.kompose.service: redis
    name: redis
spec:
    selector:
        matchLabels:
            io.kompose.service: redis
    strategy:
        type: Recreate
    template:
        metadata:
            annotations:
                kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
                    --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
                    --output-file parse2-scanagroempresa.PROD
                kompose.version: 1.21.0 (992df58d8)
            creationTimestamp: null
            labels:
                io.kompose.service: redis
        spec:
            imagePullSecrets:
              - name: dockerhub
            containers:
              - image: library/redis:4.0.11
                imagePullPolicy: ""
                name: redis
                resources: {}
                volumeMounts:
                  - mountPath: /data/
                    name: scanagroempresa-scanagroempresa-redis-data
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: scanagroempresa-scanagroempresa-redis-data
                persistentVolumeClaim:
                    claimName: scanagroempresa-scanagroempresa-redis-data
status: {}
