apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        io.rancher.container.pull_image: always
        kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
            --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
            --output-file parse2-scanagroempresa.PROD
        kompose.version: 1.21.0 (992df58d8)
        org.geonode.component: django
        org.geonode.instance.name: geonode
    creationTimestamp: null
    labels:
        io.kompose.service: worker
    name: worker
    namespace: scanagroempresa
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: worker
    strategy:
        type: Recreate
    template:
        metadata:
            # annotations:
            #     io.rancher.container.pull_image: always
            #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
            #         --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
            #         --output-file parse2-scanagroempresa.PROD
            #     kompose.version: 1.21.0 (992df58d8)
            #     org.geonode.component: django
            #     org.geonode.instance.name: geonode
            # creationTimestamp: null
            labels:
                io.kompose.service: worker
                org.geonode.component: django
                org.geonode.instance.name: geonode
        spec:
            imagePullSecrets:
              - name: dockerhub
            containers:
              - args:
                  - celery
                  - worker
                  - -A
                  - core
                  - -l
                  - debug
                  - -Q
                  - celery,default,geonode,cleanup,update,email
                  - -n
                  - geonode.%h
                  - -B
                env:
                  - name: ADMIN_EMAILS
                  - name: ALLOWED_HOSTS
                    value: '[''.scanterra.com'']'
                  - name: ASYNC_SIGNALS_GEONODE
                    value: "True"
                  - name: BROKER_URL
                    value: amqp://guest:guest@rabbitmq:5672/
                  - name: C_FORCE_ROOT
                    value: "1"
                  - name: DATABASE_HOST
                    value: db
                  - name: DATABASE_NAME
                    value: geonode
                  - name: DATABASE_PASSWORD
                    value: postgres
                  - name: DATABASE_USERNAME
                    value: postgres
                  - name: DEBUG
                    value: "False"
                  - name: DEFAULT_BACKEND_DATASTORE
                    value: datastore
                  - name: DEFAULT_FROM_EMAIL
                    value: soporte@scanterra.com
                  - name: DJANGO_SETTINGS_MODULE
                    value: core.settings.overrides
                  - name: DOCKER_ENV
                  - name: EMAIL_BACKEND
                    value: django.core.mail.backends.smtp.EmailBackend
                  - name: EMAIL_HOST
                    value: smtp
                  - name: EMAIL_HOST_PASSWORD
                    value: docker
                  - name: EMAIL_HOST_USER
                    value: noreply
                  - name: EMAIL_PORT
                    value: "25"
                  - name: EMAIL_USE_TLS
                    value: "False"
                  - name: GEOIP_PATH
                    value: /mnt/volumes/statics/geoip.db
                  - name: GEONODE_DATABASE
                    value: geonode
                  - name: GEONODE_DATABASE_PASSWORD
                    value: geonode
                  - name: GEONODE_GEODATABASE
                    value: geonode_data
                  - name: GEONODE_GEODATABASE_PASSWORD
                    value: geonode_data
                  - name: GEONODE_INDEX_PREFIX
                    value: r'^administration/?'
                  - name: GEONODE_INSTANCE_NAME
                    value: geonode
                  - name: GEONODE_PREFIX
                    value: ''''''
                  - name: GEONODE_THEME_APP_NAME
                    value: geonode_custom_theme
                  - name: GEONODE_THEME_APP_PIP_URL
                    value: git+https://github.com/kartoza/geonode_custom_theme.git@develop
                  - name: GEOSERVER_ADMIN_PASSWORD
                    value: 9Jk*8$k!mlXdgmQiPqya
                  - name: GEOSERVER_BASE_URL
                    value: https://local.scanagroempresa.scanterra.com/geoserver/
                  - name: GEOSERVER_LOCATION
                    value: http://geoserver:8080/geoserver/
                  - name: GEOSERVER_PUBLIC_LOCATION
                    value: https://local.scanagroempresa.scanterra.com/geoserver/
                  - name: IS_CELERY
                    value: "false"
                  - name: MEDIA_ROOT
                    value: /mnt/volumes/statics/uploaded/
                  - name: PYTHONPATH
                    value: /usr/src/geonode_overrides
                  - name: RANCHER_ENV
                    value: prod.scanterra
                  - name: RANCHER_STACK
                    value: scanagroempresa
                  - name: ROOT_URLCONF
                    value: core.root_urls
                  - name: SCANAGROEMPRESA_URL
                    value: https://local.scanagroempresa.scanterra.com/scanagroempresa/
                  - name: SECRET_KEY
                    value: sae8c0#cb&d-yt=d)vwf%8ks(rn_+++$za5(mv(2g#-1l9k2%f)vs
                  - name: SITEURL
                    value: https://local.scanagroempresa.scanterra.com/
                  - name: STATIC_ROOT
                    value: /mnt/volumes/statics/static/
                  - name: USE_GEONODE_THEME_APP
                    value: "True"
                  - name: USE_GEOSERVER
                    value: "True"
                  - name: UWSGI_CMD
                    value: uwsgi --ini /usr/src/app/uwsgi.ini
                  - name: DATABASE_URL
                    value: postgres://geonode:geonode@db:5432/geonode
                  - name: GEODATABASE_URL
                    value: postgis://geonode_data:geonode_data@db:5432/geonode_data
                image: marcelorubini/geonode_generic:removes-models-cp
                imagePullPolicy: Always
                name: worker
                resources: {}
                stdin: true
                volumeMounts:
                  - mountPath: /mnt/volumes/statics
                    name: scanagroempresa-statics
                  - mountPath: /usr/src/app/geonode_generic/templates
                    name: templates
            restartPolicy: Always
            serviceAccountName: ""
            volumes:
              - name: scanagroempresa-statics
                persistentVolumeClaim:
                    claimName: scanagroempresa-statics
              - name: templates
                persistentVolumeClaim:
                    claimName: templates
status: {}
