apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: scanagroempresa-borg-cache
    name: scanagroempresa-borg-cache
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
status: {}
