apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: scanagroempresa-geonode-ssh-config
    name: scanagroempresa-geonode-ssh-config
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: local-storage
    volumeMode: Filesystem
    volumeName: scanagroempresa-geonode-ssh-config
status: {}
