apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: scanagroempresa-statics
    name: scanagroempresa-statics
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: local-storage
    volumeMode: Filesystem
    volumeName: scanagroempresa-statics
status: {}
