apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: scanagroempresa-scanagroempresa-ssh-config
    name: scanagroempresa-scanagroempresa-ssh-config
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
status: {}
