apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: scanagroempresa-geoserver-data-dir
    name: scanagroempresa-geoserver-data-dir
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: local-storage
    volumeMode: Filesystem
    volumeName: scanagroempresa-geoserver-data-dir
status: {}
