apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: templates
    name: templates
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: local-storage
    volumeMode: Filesystem
    volumeName: templates
status: {}
