apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:scanagroempresa:django"]'
  name: django
  namespace: scanagroempresa
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workloadID_django: "true"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
