apiVersion: v1
kind: Service
metadata:
    # annotations:
    #     io.rancher.container.pull_image: always
    #     io.rancher.scheduler.affinity:host_label: geonode.production=geonode
    #     kompose.cmd: ./migration-tools-0.1.3 parse --docker-file export/scanterra.PROD/scanagroempresa/docker-compose.yml
    #         --rancher-file export/scanterra.PROD/scanagroempresa/rancher-compose.yml
    #         --output-file parse2-scanagroempresa.PROD
    #     kompose.version: 1.21.0 (992df58d8)
    #     org.geonode.component: nginx
    #     org.geonode.instance.name: geonode
    # creationTimestamp: null
    labels:
        io.kompose.service: geonode
    name: geonode
    namespace: scanagroempresa
spec:
    ports:
      - name: "71"
        port: 71
        targetPort: 80
    selector:
        io.kompose.service: geonode
status:
    loadBalancer: {}
