{{ range .Values.deployments.definitions }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .name }}
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .name }}
      {{- if not (empty .annotations) }}
      annotations:
        {{- with .annotations }}
          {{- toYaml . | trim | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        imagePullPolicy: {{ .imagePullPolicy }}
        {{- if not (empty .args) }}
        args:
          {{- with .args }}
            {{- toYaml . | trim | nindent 10 }}
          {{- end }}
        {{- end }}
        {{- if not (empty .envs) }}
        env:
          {{- with .envs }}
            {{- toYaml . | trim | nindent 10 }}
          {{- end }}
        {{- end }}
        {{- if not (empty .mounts) }}
        volumeMounts:
          {{- with .mounts }}
            {{- toYaml . | trim | nindent 10 }}
          {{- end }}
        {{- end }}                
      imagePullSecrets:
      {{- with $.Values.pullSecrets }}
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      restartPolicy: {{ $.Values.restartPolicy }}
      serviceAccountName: ""
      {{- if not (empty .volumes) }}
      volumes:
        {{- with .volumes }}
          {{- toYaml . | trim | nindent 8 }}
        {{- end }}
      {{- end }}
status: {}
{{ end }}
